site:
  full_name: SB
  short_name: Silvestar Bistrović
  description: Silvestar Bistrović is fearless web developer, CSS craftsman, JAMstack enthusiast, and WordPress theme specialist.
  logo: /gfx/svg/logo.svg
  logo_footer: /gfx/svg/logo-footer.svg
  language: en-US

home_page:
  - section:
    position: alpha
    title: Silvestar Bistrović
    profile: //res.cloudinary.com/starbist/image/upload/v1545137170/profile_tsqb7d.png
    profilealt: Headshot of myself, Silvestar Bistrović
    headings:
     - Fearless web developer
     - CSS craftsman
     - JAMstack enthusiast
     - WordPress theme specialist
    list_class: beta
  - section:
    position: beta
    title: Featured Articles
    images:
      - src: //res.cloudinary.com/starbist/image/upload/v1551783370/Custom_WordPress_Theme_Development_with_SPRO_koknho.jpg
        title: 'Custom WordPress Theme Development with SPRO'
        alt: 'Cover image with custom graphics for article Custom WordPress Theme Development with SPRO.'
        href: /articles/custom-wordpress-theme-development-with-spro/
      - src: //res.cloudinary.com/starbist/image/upload/v1544203449/Building_an_animated_sticky_header_with_custom_offset_pnzuri.jpg
        title: 'Building an Animated Sticky Header With Custom Offset'
        alt: 'Cover image with custom graphics for article Building an Animated Sticky Header With Custom Offset.'
        href: /articles/building-an-animated-sticky-header-with-custom-offset/
      - src: //res.cloudinary.com/starbist/image/upload/v1535357269/Overview_of_Popular_Static_Site_Generators_fpv8q9.jpg
        title: 'Overview of Popular Static Site Generators'
        alt: 'Cover image with custom graphics for article Overview of Popular Static Site Generators.'
        href: /articles/overviev-of-popular-static-site-generators/
      - src: //res.cloudinary.com/starbist/image/upload/v1536138845/Using_CSS_Grid_where_appropriate_revisited_m4mtyq.jpg
        title: 'Using CSS Grid where appropriate (revisited)'
        alt: 'Cover image with custom graphics for article Using CSS Grid where appropriate (revisited).'
        href: /articles/using-css-grid-where-appropriate-revisited/
    links:
      See all articles →: /categories/articles/
  - section:
    position: gamma
    title: Contact
    links:
      Contact: https://silvestar.typeform.com/to/jS4Qkz
      Skype: //join.skype.com/invite/jtWeft24StMV
      LinkedIn: //www.linkedin.com/in/starbist/
      Twitter: //twitter.com/malimirkeccita
    list_class: gamma
  - section:
    position: delta
    title: Profiles
    links:
      Toptal: //www.toptal.com/resume/silvestar-bistrovic#trust-nothing-but-brilliant-freelancers
      LinkedIn: //www.linkedin.com/in/starbist/
      GitHub: //github.com/maliMirkec
      CodePen: //codepen.io/CiTA/
    list_class: gamma
  - section:
    position: epsilon
    title: Projects
    images:
      - src: //res.cloudinary.com/starbist/image/upload/v1549951653/ddl_mypfrt.png
        title: Domino Data Lab
        alt: Domino Data Lab website displayed on laptop, tablet, and mobile device.
        href: /portfolio/dominodatalab/
      - src: //res.cloudinary.com/starbist/image/upload/v1533798343/ww_hceizq.png
        title: Westwing
        alt: Westwing website displayed on laptop, tablet, and mobile device.
        href: /portfolio/westwing/
      - src: //res.cloudinary.com/starbist/image/upload/v1533798334/b_csao4p.png
        title: Bozzuto
        alt: Bozzuto website displayed on laptop, tablet, and mobile device.
        href: /portfolio/bozzuto/
      - src: //res.cloudinary.com/starbist/image/upload/v1526983573/c_ob598q.png
        title: Contiamo
        alt: Contiamo website displayed on laptop, tablet, and mobile device.
        href: /portfolio/contiamo/
    links:
      See all projects →: /portfolio/
  - section:
    position: omega
    list_class: omega
    title: Testimonials
    quotes:
      - person: Evan Lavidor
        position: Partner & Executive Director
        project:
          name: BEAM Interactive
          link: /portfolio/flexera/
        paragraphs:
          - We've worked with Silvestar on several projects, and he's been a pleasure to work with on all of them. Recently, he handled primary front end development for two large web sites that were launched on Adobe Experience Manager. He's also worked on the front end development of a large WordPress project as well as some smaller campaign landing page and microsite work.
          - In all cases, Silvestar's been a breeze to work with. Communication is easy, and he's happy to be part of a larger team, attend regular standups, stay in close communication electronically, etc. (a key factor when working across countries/time zones).
          - His approach to front end development is modern, but he still knows how to debug for Internet Explorer and handle browser-specific issues. He's a thorough tester and has a great eye for detail.
          - Additionally, he's very fast. We were always impressed with the speed at which he could put things together at a very high level of quality.
          - I'd happily work with Silvestar again, and we'll definitely reach out to him in the future when we need help with additional projects.
      - person: Han Han Xue
        position: Product Designer
        project:
          name: Lyft
          link: /portfolio/hanhanxue/
        paragraphs:
          - I collaborated closely with Silvestar on a project.
          - Throughout the span of the project, Silvestar was able to consistently meet if not exceed expectations. He has the impressive ability to not only readily undertake direct requests, but also intuitively distill ambiguous asks in order to execute solves in a self-sufficient manner.
          - Silvestar’s can-do attitude and palpable passion for the work combined with his extended knowledge makes for a highly effective problem solver who always strives to provide the best solutions.
          - If you aim for not only high standard in the result but also elegance in the process, then I would highly recommend considering Silvestar for your project."
      - person: Adam Maschek
        position: CTO at Westwing Home & Living
        project:
          name: Westwing
          link: /portfolio/westwing/
        paragraphs:
          - It was a pleasure to work with Silvestar. He was available on a short notice, he closely collaborated with the PM on the project and delivered it on time with good quality. I would work with him again, and actually we are considering to kick off our next project with him.
      - person: Karim Mansi
        position: eCommerce Product Manager at Westwing Home & Living
        project:
          name: Westwing
          link: /portfolio/westwing/
        paragraphs:
          - While working a senior Product Manager at Westwing Home & Living, I had the pleasure to hire Silvestar to build our static corporate website. The project went very smoothly and was delivered on time. Communication with Silvestar was straightforward, clear and reliable. He was also very resourceful and what he didn't know he figured out on his own. I would definitely recommend him for static web solutions and other web front-end projects.
      - person: Pablo Pareja Tobes
        position: Project Manager
        project:
          name: Vizzuality
          link: /portfolio/yearbook-trase/
        paragraphs:
          - Silvestar collaborated with me on a project and the WordPress template that he developed was successful and timely completed. He was professional and had a very good attitude during all the implementation time. I would work with him again should the occasion arise.

open_graph:
  pretty_url: true
  image: /gfx/jpg/logo.jpg
  fb:
    fb_id: 340933169673372
    fb_admins: malimirkeccita
  twitter:
    twitter_id: malimirkeccita
  google_plus:
    google_plus_id: +SilvestarbistrovicFromHr

menu:
  centered: true
  display_logo: false
  items:
    Home: /
    Blog: /categories/articles/
    Portfolio: /portfolio/
    About: /about-me/
    Connect: /links/
    Contact →: https://silvestar.typeform.com/to/jS4Qkz

portfolio:
  title: Projects
  items:
    # Calvert: /portfolio/calvert/
    Flexera: /portfolio/flexera/
    Flexera Software: /portfolio/flexerasoftware/
    Machine Learning Libraries: /portfolio/machine-learning-libraries/
    Domino Data Lab: /portfolio/dominodatalab/
    Domino Data Lab Rev: /portfolio/dominodatalab-rev/
    Domino Data Lab Pop-up: /portfolio/dominodatalab-pop-up/
    TheGrio: /portfolio/thegrio/
    Westwing: /portfolio/westwing/
    Bozzuto: /portfolio/bozzuto/
    Trase Yearbook 2018: /portfolio/yearbook-trase/
    Netki: /portfolio/netki/
    Han Han Xue: /portfolio/hanhanxue/
    Contiamo: /portfolio/contiamo/
    Moodings: /portfolio/moodings/
    Irina & Matej: /portfolio/irinaandmatej/

sidebar:
  title: Links
  items:
    Contact: https://silvestar.typeform.com/to/jS4Qkz
    About: /about-me/
    Hire me: /hire-me/
    Services: /services/
    Setup: /uses/
    Links: /links/
    CV: /portfolio/silvestar-bistrovic-cv.pdf
    Toptal: //www.toptal.com/resume/silvestar-bistrovic#trust-nothing-but-brilliant-freelancers
    LinkedIn: //www.linkedin.com/in/starbist/
    GitHub: //github.com/maliMirkec
    CodePen: //codepen.io/CiTA/
    Twitter: //twitter.com/malimirkeccita
    Silvestar Bistrović: /

banner1:
  span: "I am currently considering new projects for this year. Contact me if you want me on your team."
  btn1: "Get in touch"
  btn2: "I am open for new projects"
  link: https://silvestar.typeform.com/to/jS4Qkz

banner2:
  span: "I am currently considering new projects for this year. Contact me."
  btn1: "Get in touch"
  btn2: "I am open for new projects"
  href: https://silvestar.typeform.com/to/jS4Qkz

widgets:
  cookies:
    paragraph: This site uses cookies to count visitors anonymously.
  about:
    paragraphs:
      - I am Silvestar Bistrović, fearless web developer, JAMstack enthusiast and WordPress coder.
    contact:
      Contact: https://silvestar.typeform.com/to/jS4Qkz
      Toptal: //www.toptal.com/resume/silvestar-bistrovic#trust-nothing-but-brilliant-freelancers
      LinkedIn: //www.linkedin.com/in/starbist/
      GitHub: //github.com/maliMirkec
      CodePen: //codepen.io/CiTA/
      Twitter: //twitter.com/malimirkeccita
  subnav:
    Silvestar Bistrović: /
    Contact: https://silvestar.typeform.com/to/jS4Qkz
    Toptal: //www.toptal.com/resume/silvestar-bistrovic#trust-nothing-but-brilliant-freelancers
    LinkedIn: //www.linkedin.com/in/starbist/
    GitHub: //github.com/maliMirkec
    CodePen: //codepen.io/CiTA/
    Twitter: //twitter.com/malimirkeccita
    Feed: //www.silvestar.codes/rss2.xml
  disqus:
    shortname: silvestarbistrovic
  sharing:
    twitter: malimirkeccita
    facebook: silvestar.codes
    reddit: true
