site:
  full_name: Silvestar Bistrović—fearless web developer, CSS craftsman, JAMstack enthusiast, and Wordpress theme specialist.
  short_name: Silvestar Bistrović
  description: Silvestar Bistrović is fearless web developer, CSS craftsman, JAMstack enthusiast, and Wordpress theme specialist.
  logo: /gfx/svg/logo.svg
  logo_footer: /gfx/svg/logo-footer.svg
  language: en-US

home_page:
  - section:
    position: alpha
    title: Silvestar Bistrović
    profile: //res.cloudinary.com/starbist/image/upload/v1545137170/profile_tsqb7d.png
    headings:
     - Fearless web developer
     - CSS craftsman
     - JAMstack enthusiast
     - Wordpress theme specialist
    list_class: beta
  - section:
    position: gamma
    title: Projects
    images:
      - src: //res.cloudinary.com/starbist/image/upload/v1533798343/ww_hceizq.png
        title: Westwing
        href: /portfolio/westwing/
      - src: //res.cloudinary.com/starbist/image/upload/v1533798334/b_csao4p.png
        title: Bozzuto
        href: /portfolio/bozzuto/
      - src: //res.cloudinary.com/starbist/image/upload/v1526983574/hhx_p45br6.png
        title: Han Han Xue
        href: /portfolio/hanhanxue/
      - src: //res.cloudinary.com/starbist/image/upload/v1526983573/c_ob598q.png
        title: Contiamo
        href: /portfolio/contiamo/
    links:
      See all projects →: /portfolio/
  - section:
    position: beta
    title: Featured Articles
    images:
      - src: //res.cloudinary.com/starbist/image/upload/v1546701300/2018-lookback-2x_xvi1vo.jpg
        title: 2018 Lookback
        href: /articles/2018-lookback/
      - src: //res.cloudinary.com/starbist/image/upload/v1544203449/Building_an_animated_sticky_header_with_custom_offset_pnzuri.jpg
        title: Building an animated sticky header with custom offset
        href: /articles/building-an-animated-sticky-header-with-custom-offset/
      - src: //res.cloudinary.com/starbist/image/upload/v1536138845/Using_CSS_Grid_where_appropriate_revisited_m4mtyq.jpg
        title: 'Using CSS Grid where appropriate (revisited)'
        href: /articles/using-css-grid-where-appropriate-revisited/
      - src: //res.cloudinary.com/starbist/image/upload/v1535357269/Overview_of_Popular_Static_Site_Generators_fpv8q9.jpg
        title: Overview of Popular Static Site Generators
        href: /articles/overviev-of-popular-static-site-generators/
    links:
      See all articles →: /categories/articles/
  - section:
    position: delta
    title: Contact
    links:
      Contact: https://silvestar.typeform.com/to/jS4Qkz
      Skype: //join.skype.com/invite/jtWeft24StMV
      LinkedIn: //www.linkedin.com/in/starbist/
      Twitter: //twitter.com/malimirkeccita
    list_class: gamma
  - section:
    position: epsilon
    title: Profiles
    links:
      Toptal: //www.toptal.com/resume/silvestar-bistrovic#trust-nothing-but-brilliant-freelancers
      LinkedIn: //www.linkedin.com/in/starbist/
      GitHub: //github.com/maliMirkec
      CodePen: //codepen.io/CiTA/
    list_class: gamma
  - section:
    position: omega
    title: Testimonials
    quotes:
      - person: Adam Maschek
        position: CTO at Westwing Home & Living
        project:
          name: Westwing
          link: /portfolio/westwing/
        text: "It was a pleasure to work with Silvestar. He was available on a short notice, he closely collaborated with the PM on the project and delivered it on time with good quality. I would work with him again, and actually we are considering to kick off our next project with him."
      - person: Pablo Pareja Tobes
        position: Project Manager at Vizzuality
        project:
          name: Trase Yearbook 2018
          link: /portfolio/yearbook-trase/
        text: "Silvestar collaborated with me on a project and the WordPress template that he developed was successful and timely completed. He was professional and had a very good attitude during all the implementation time. I would work with him again should the occasion arise."
      - person: Karim Mansi
        position: eCommerce Product Manager
        project:
          name: Westwing
          link: /portfolio/westwing/
        text: "While working a senior Product Manager at Westwing Home & Living, I had the pleasure to hire Silvestar to build our static corporate website. The project went very smoothly and was delivered on time. Communication with Silvestar was straightforward, clear and reliable. He was also very resourceful and what he didn't know he figured out on his own. I would definitely recommend him for static web solutions and other web front-end projects."
      - person: Han Han Xue
        position: Product Designer at Lyft
        project:
          name: Han Han Xue
          link: /portfolio/hanhanxue/
        text: "I collaborated closely with Silvestar on a project.

        Throughout the span of the project, Silvestar was able to consistently meet if not exceed expectations. He has the impressive ability to not only readily undertake direct requests, but also intuitively distill ambiguous asks in order to execute solves in a self-sufficient manner.

        Silvestar’s can-do attitude and palpable passion for the work combined with his extended knowledge makes for a highly effective problem solver who always strives to provide the best solutions.

        If you aim for not only high standard in the result but also elegance in the process, then I would highly recommend considering Silvestar for your project."
    list_class: omega

open_graph:
  pretty_url: true
  image: /gfx/jpg/logo.jpg
  fb:
    fb_id: 340933169673372
    fb_admins: malimirkeccita
  twitter:
    twitter_id: malimirkeccita
  google_plus:
    google_plus_id: +SilvestarbistrovicFromHr

menu:
  centered: true
  display_logo: false
  items:
    Home: /
    Blog: /categories/articles
    Portfolio: /portfolio
    About: /about-me
    Links: /links
    Contact: https://silvestar.typeform.com/to/jS4Qkz

portfolio:
  title: Projects
  items:
    Westwing: /portfolio/westwing/
    Bozzuto: /portfolio/bozzuto/
    Trase Yearbook 2018: /portfolio/yearbook-trase/
    Netki: /portfolio/netki/
    Han Han Xue: /portfolio/hanhanxue/
    Contiamo: /portfolio/contiamo/
    Moodings: /portfolio/moodings/
    Irina & Matej: /portfolio/irinaandmatej/

sidebar:
  title: Links
  items:
    About: /about-me/
    Links: /links/
    Hire ME: /hire-me/
    Setup: /uses/
    Contact: https://silvestar.typeform.com/to/jS4Qkz
    Toptal: //www.toptal.com/resume/silvestar-bistrovic#trust-nothing-but-brilliant-freelancers
    LinkedIn: //www.linkedin.com/in/starbist/
    GitHub: //github.com/maliMirkec
    CodePen: //codepen.io/CiTA/
    Twitter: //twitter.com/malimirkeccita
    Silvestar Bistrović: /

banner1:
  span: "I am currently considering new projects for this year. Contact me if you want me on your team."
  btn1: "Get in touch"
  btn2: "2019 Q2-Q3"
  link: https://silvestar.typeform.com/to/jS4Qkz

banner2:
  span: "I am currently considering new projects for this year. Contact me."
  btn1: "Get in touch"
  btn2: "2019 Q2-Q3"
  href: https://silvestar.typeform.com/to/jS4Qkz

widgets:
  about:
    paragraphs:
      - I am Silvestar Bistrović, fearless web developer, JAMstack enthusiast and WordPress coder.
    contact:
      Contact: https://silvestar.typeform.com/to/jS4Qkz
      Toptal: //www.toptal.com/resume/silvestar-bistrovic#trust-nothing-but-brilliant-freelancers
      LinkedIn: //www.linkedin.com/in/starbist/
      GitHub: //github.com/maliMirkec
      CodePen: //codepen.io/CiTA/
      Twitter: //twitter.com/malimirkeccita
  subnav:
    Silvestar Bistrović: /
    Contact: https://silvestar.typeform.com/to/jS4Qkz
    Toptal: //www.toptal.com/resume/silvestar-bistrovic#trust-nothing-but-brilliant-freelancers
    LinkedIn: //www.linkedin.com/in/starbist/
    GitHub: //github.com/maliMirkec
    CodePen: //codepen.io/CiTA/
    Twitter: //twitter.com/malimirkeccita
    Feed: //www.silvestarbistrovic.from.hr/rss2.xml
  disqus:
    shortname: silvestarbistrovic
  sharing:
    twitter: malimirkeccita
    facebook: silvestarbistrovic.from.hr
    reddit: true
