site:
  full_name: SB - Silvestar's personal website
  short_name: Silvestar Bistrović
  description: Silvestar Bistrović is fearless web developer, JAMstack enthusiast, Wordpress coder and blog writer.
  logo: /gfx/svg/logo.svg
  logo_footer: /gfx/svg/logo-footer.svg
  language: en

home_page:
  - section:
    position: alpha
    title: Silvestar Bistrović
    headings:
     - Fearless web developer
     - JAMstack enthusiast
     - Wordpress coder
     - Blog writer
    list_class: beta
  - section:
    position: gamma
    title: Projects
    images:
      - src: //res.cloudinary.com/starbist/image/upload/v1526983575/n_gcmcap.png
        title: Netki
        href: /portfolio/netki/
      - src: //res.cloudinary.com/starbist/image/upload/v1526983574/hhx_p45br6.png
        title: Han Han Xue
        href: /portfolio/hanhanxue/
      - src: //res.cloudinary.com/starbist/image/upload/v1526983573/c_ob598q.png
        title: Contiamo
        href: /portfolio/contiamo/
      - src: //res.cloudinary.com/starbist/image/upload/v1526983574/m_rjmzz2.png
        title: Moodings
        href: /portfolio/moodings/
  - section:
    position: beta
    title: Featured Articles
    images:
      - src: //res.cloudinary.com/starbist/image/upload/v1531903322/The_Essential_Skill_Of_A_Developer_csb5dm.jpg
        title: The Essential Skill Of A Developer
        href: /articles/modern-frontend-developer-skills-and-tools/
      - src: //res.cloudinary.com/starbist/image/upload/v1526981223/My_first_year_of_freelancing_exsbxg.jpg
        title: My first year of freelancing
        href: /articles/my-first-year-of-freelancing/
      - src: //res.cloudinary.com/starbist/image/upload/v1508398026/From_WordPress_to_Hexo_xgibru.png
        title: From Wordpress to Hexo
        href: /articles/a-guide-to-static-site-generators-using-hexo-and-wordpress/
      - src: //res.cloudinary.com/starbist/image/upload/v1501440293/Using_CSS_Grid_where_appropriate_aelnvq.png
        title: Using CSS Grid Where Appropriate
        href: /articles/using-css-grid-where-appropriate/
  - section:
    position: delta
    title: Links
    links:
      Toptal: //www.toptal.com/resume/silvestar-bistrovic#trust-nothing-but-brilliant-freelancers
      LinkedIn: //www.linkedin.com/in/starbist/
      GitHub: //github.com/maliMirkec
      CodePen: //codepen.io/CiTA/
    list_class: gamma
  - section:
    position: epsilon
    title: Hire me
    links:
      Via Mail: mailto:me@silvestarbistrovic.from.hr?Subject=Inquiry
      Via Toptal: //www.toptal.com/resume/silvestar-bistrovic#trust-nothing-but-brilliant-freelancers
      Via Upwork: //www.upwork.com/fl/silvestarb
      Via Codementor: //www.codementor.io/malimirkeccita
    list_class: gamma

open_graph:
  pretty_url: true
  image: /gfx/png/SB-big.png
  fb:
    fb_id: 340933169673372
    fb_admins: malimirkeccita
  twitter:
    twitter_id: malimirkeccita
  google_plus:
    google_plus_id: +SilvestarbistrovicFromHr

menu:
  centered: true
  display_logo: false
  items:
    Home: /
    Blog: /categories/articles
    Portfolio: /portfolio
    About: /about-me
    Starter Project: //starter.silvestarbistrovic.from.hr

widgets:
  info:
    paragraphs:
      - I am Silvestar Bistrović, fearless web developer, JAMstack enthusiast and WordPress coder.
      - I am currently considering new projects. Contact me!
    cta:
      Contact me!: mailto:me@silvestarbistrovic.from.hr?Subject=New%20;Project
    contact:
      Mail: mailto:me@silvestarbistrovic.from.hr?Subject=Hello
      Toptal: //www.toptal.com/resume/silvestar-bistrovic#trust-nothing-but-brilliant-freelancers
      LinkedIn: //www.linkedin.com/in/starbist/
      GitHub: //github.com/maliMirkec
      CodePen: //codepen.io/CiTA/
      Twitter: //twitter.com/malimirkeccita
  subnav:
    Silvestar Bistrović: /
    Mail: mailto:me@silvestarbistrovic.from.hr?Subject=Hello
    Toptal: //www.toptal.com/resume/silvestar-bistrovic#trust-nothing-but-brilliant-freelancers
    LinkedIn: //www.linkedin.com/in/starbist/
    GitHub: //github.com/maliMirkec
    CodePen: //codepen.io/CiTA/
    Twitter: //twitter.com/malimirkeccita
  disqus:
    shortname: silvestarbistrovic
  sharing:
    twitter: malimirkeccita
    facebook: silvestarbistrovic.from.hr
    reddit: true
