site:
  full_name: SB
  short_name: Silvestar Bistrović
  description: Silvestar Bistrović is fearless web developer, CSS craftsman, JAMstack enthusiast, and WordPress theme specialist.
  logo: /gfx/svg/logo.svg
  logo_footer: /gfx/svg/logo-footer.svg
  language: en-US

home_page:
  - section:
    position: alpha
    title: Silvestar Bistrović
    id: Profile
    profile: https://res.cloudinary.com/starbist/image/upload/v1545137170/profile_tsqb7d.png
    profilealt: Headshot of myself, Silvestar Bistrović
    headings:
     - Fearless web developer
     - CSS craftsman
     - JAMstack enthusiast
     - WordPress theme specialist
    list_class: beta
  - section:
    position: beta
    title: Featured Articles
    id: FeaturedArticles
    images:
      - src: https://res.cloudinary.com/starbist/image/upload/v1557942398/Oh_the_Many_Ways_to_Make_Triangular_Breadcrumb_Ribbons-2x_y1lftp.jpg
        title: '💫 Oh, the Many Ways to Make Triangular Breadcrumb Ribbons!'
        alt: 'Cover image with custom graphics for article Oh, the Many Ways to Make Triangular Breadcrumb Ribbons.'
        href: /articles/oh-the-many-ways-to-make-triangular-breadcrumb-ribbons/
      - src: https://res.cloudinary.com/starbist/image/upload/v1557942405/5_things_to_consider_when_creating_your_CSS_style_guide-2x_gfuzck.jpg
        title: '💫 5 things to consider when creating your CSS style guide'
        alt: 'Cover image with custom graphics for article 5 things to consider when creating your CSS style guide.'
        href: /articles/5-things-to-consider-when-creating-your-css-style-guide/
      - src: https://res.cloudinary.com/starbist/image/upload/v1551783370/Custom_WordPress_Theme_Development_with_SPRO_koknho.jpg
        title: '💫 Custom WordPress Theme Development with SPRO'
        alt: 'Cover image with custom graphics for article Custom WordPress Theme Development with SPRO.'
        href: /articles/custom-wordpress-theme-development-with-spro/
      - src: https://res.cloudinary.com/starbist/image/upload/v1544203449/Building_an_animated_sticky_header_with_custom_offset_pnzuri.jpg
        title: '💫 Building an Animated Sticky Header With Custom Offset'
        alt: 'Cover image with custom graphics for article Building an Animated Sticky Header With Custom Offset.'
        href: /articles/building-an-animated-sticky-header-with-custom-offset/
    links:
      See all articles →: /categories/articles/
  - section:
    position: gamma
    title: Publications
    id: Publications
    images:
      - src: https://res.cloudinary.com/starbist/image/upload/v1557668111/css-tricks-triangular-breadcrumb_wtapyn.jpg
        title: "⭐️ CSS Tricks: Oh, the Many Ways to Make Triangular Breadcrumb Ribbons!"
        alt: "Screenshot of an article from CSS Tricks"
        href: https://css-tricks.com/oh-the-many-ways-to-make-triangular-breadcrumb-ribbons/
      - src: https://res.cloudinary.com/starbist/image/upload/v1557668111/logrocket-css-style-guide_ca7glk.jpg
        title: "⭐️ LogRocket blog: 5 things to consider when creating your CSS style guide"
        alt: "Screenshot of an article from LogRocket"
        href: https://blog.logrocket.com/5-things-to-consider-when-creating-your-css-style-guide-7b85fa70039d
      - src: https://res.cloudinary.com/starbist/image/upload/v1557668110/toptal-ssg-overview_yo8dcs.jpg
        title: "⭐️ Toptal blog: Overview of Popular Static Site Generators"
        alt: "Screenshot of an article from Toptal"
        href: https://www.toptal.com/front-end/static-site-generators-comparison-2018
      - src: https://res.cloudinary.com/starbist/image/upload/v1557668111/toptal-ssg-wordpress_ktajsm.jpg
        title: "⭐️ Toptal blog: A Guide to Static Site Generators Using Hexo and WordPress"
        alt: "Screenshot of an article from Toptal"
        href: https://www.toptal.com/front-end/wordpress-to-html-with-hexo-blog
  - section:
    position: epsilon
    title: Projects
    id: Projects
    images:
      - src: https://res.cloudinary.com/starbist/image/upload/v1549951653/ddl_mypfrt.png
        title: 🌟 Domino Data Lab
        alt: Domino Data Lab website screenshots displayed on laptop, tablet, and mobile device.
        href: /portfolio/dominodatalab/
      - src: https://res.cloudinary.com/starbist/image/upload/v1533798343/ww_hceizq.png
        title: 🌟 Westwing
        alt: Westwing website screenshots displayed on laptop, tablet, and mobile device.
        href: /portfolio/westwing/
      - src: https://res.cloudinary.com/starbist/image/upload/v1533798334/b_csao4p.png
        title: 🌟 Bozzuto
        alt: Bozzuto website screenshots displayed on laptop, tablet, and mobile device.
        href: /portfolio/bozzuto/
      - src: https://res.cloudinary.com/starbist/image/upload/v1526983573/c_ob598q.png
        title: 🌟 Contiamo
        alt: Contiamo website screenshots displayed on laptop, tablet, and mobile device.
        href: /portfolio/contiamo/
    links:
      See all projects →: /portfolio/
  - section:
    position: omega
    list_class: omega
    title: Testimonials
    id: Testimonials
    quotes:
      - person: Evan Lavidor
        position: Partner & Executive Director
        project:
          name: BEAM Interactive
          link: /portfolio/bozzuto/
        paragraphs:
          - We've worked with Silvestar on several projects, and he's been a pleasure to work with on all of them. Recently, he handled primary front end development for two large web sites that were launched on Adobe Experience Manager. He's also worked on the front end development of a large WordPress project as well as some smaller campaign landing page and microsite work.
          - In all cases, Silvestar's been a breeze to work with. Communication is easy, and he's happy to be part of a larger team, attend regular standups, stay in close communication electronically, etc. (a key factor when working across countries/time zones).
          - His approach to front end development is modern, but he still knows how to debug for Internet Explorer and handle browser-specific issues. He's a thorough tester and has a great eye for detail.
          - Additionally, he's very fast. We were always impressed with the speed at which he could put things together at a very high level of quality.
          - I'd happily work with Silvestar again, and we'll definitely reach out to him in the future when we need help with additional projects.
      - person: Han Han Xue
        position: Product Designer
        project:
          name: Lyft
          link: /portfolio/hanhanxue/
        paragraphs:
          - I collaborated closely with Silvestar on a project.
          - Throughout the span of the project, Silvestar was able to consistently meet if not exceed expectations. He has the impressive ability to not only readily undertake direct requests, but also intuitively distill ambiguous asks in order to execute solves in a self-sufficient manner.
          - Silvestar’s can-do attitude and palpable passion for the work combined with his extended knowledge makes for a highly effective problem solver who always strives to provide the best solutions.
          - If you aim for not only high standard in the result but also elegance in the process, then I would highly recommend considering Silvestar for your project."
      - person: Karim Mansi
        position: eCommerce Product Manager at Westwing Home & Living
        project:
          name: Westwing
          link: /portfolio/westwing/
        paragraphs:
          - While working a senior Product Manager at Westwing Home & Living, I had the pleasure to hire Silvestar to build our static corporate website. The project went very smoothly and was delivered on time. Communication with Silvestar was straightforward, clear and reliable. He was also very resourceful and what he didn't know he figured out on his own. I would definitely recommend him for static web solutions and other web front-end projects.
      - person: Pablo Pareja Tobes
        position: Project Manager
        project:
          name: Vizzuality
          link: /portfolio/yearbook-trase/
        paragraphs:
          - Silvestar collaborated with me on a project and the WordPress template that he developed was successful and timely completed. He was professional and had a very good attitude during all the implementation time. I would work with him again should the occasion arise.

open_graph:
  pretty_url: true
  image: /gfx/jpg/logo.jpg
  fb:
    fb_id: 340933169673372
    fb_admins: malimirkeccita
  twitter:
    twitter_id: malimirkeccita
  google_plus:
    google_plus_id: +SilvestarbistrovicFromHr

menu:
  centered: true
  display_logo: false
  items:
    Home: /
    Blog: /categories/articles/
    Portfolio: /portfolio/
    About: /about-me/
    My links: /links/
    Contact →: /contact/

portfolio:
  title: Projects
  items:
    Calvert: /portfolio/calvert/
    Domino Data Lab: /portfolio/dominodatalab/
    Domino Data Lab Rev: /portfolio/dominodatalab-rev/
    Domino Data Lab Pop-up: /portfolio/dominodatalab-pop-up/
    Machine Learning Libraries: /portfolio/machine-learning-libraries/
    Westwing: /portfolio/westwing/
    Bozzuto: /portfolio/bozzuto/
    TheGrio: /portfolio/thegrio/
    Trase Yearbook 2018: /portfolio/yearbook-trase/
    Netki: /portfolio/netki/
    Contiamo: /portfolio/contiamo/
    Moodings: /portfolio/moodings/
    Han Han Xue: /portfolio/hanhanxue/
    Irina & Matej: /portfolio/irinaandmatej/

sidebar:
  title: Quick Links
  items:
    Contact: /contact/
    About: /about-me/
    Hire me: /hire-me/
    Services: /services/
    Setup: /uses/
    My Links: /links/
    CV: /portfolio/silvestar-bistrovic-cv.pdf
    # Toptal: https://www.toptal.com/resume/silvestar-bistrovic#trust-nothing-but-brilliant-freelancers
    LinkedIn: https://www.linkedin.com/in/starbist/
    GitHub: https://github.com/maliMirkec
    CodePen: https://codepen.io/CiTA/
    Twitter: https://twitter.com/malimirkeccita
    Silvestar Bistrović: /

banner1:
  span: "I am currently considering new projects for this year. Contact me if
  you want me on your team."
  btn1: "👉 Get in touch"
  btn2: "I am open for new projects"
  link: /contact/

banner2:
  span: "I am currently considering new projects for this year. Contact me."
  btn1: "👉 Get in touch"
  btn2: "I am open for new projects"
  href: /contact/

widgets:
  cookies:
    paragraph: This site uses cookies to count visitors anonymously.
  about:
    paragraphs:
      - I am Silvestar Bistrović, fearless web developer, JAMstack enthusiast and WordPress coder.
    contact:
      Contact: /contact/
      # Toptal: https://www.toptal.com/resume/silvestar-bistrovic#trust-nothing-but-brilliant-freelancers
      LinkedIn: https://www.linkedin.com/in/starbist/
      GitHub: https://github.com/maliMirkec
      CodePen: https://codepen.io/CiTA/
      Twitter: https://twitter.com/malimirkeccita
  subnav:
    Silvestar Bistrović: /
    Contact: /contact/
    # Toptal: https://www.toptal.com/resume/silvestar-bistrovic#trust-nothing-but-brilliant-freelancers
    LinkedIn: https://www.linkedin.com/in/starbist/
    GitHub: https://github.com/maliMirkec
    CodePen: https://codepen.io/CiTA/
    Twitter: https://twitter.com/malimirkeccita
    Feed: https://www.silvestar.codes/rss2.xml
  disqus:
    shortname: silvestarbistrovic
  sharing:
    twitter: malimirkeccita
    facebook: silvestar.codes
    reddit: true
