site:
  full_name: SB
  short_name: Silvestar Bistrović
  title: Home of Silvestar Bistrović
  description: Home of Silvestar Bistrović—fearless web engineer, CSS developer, JAMstack enthusiast, and WordPress theme specialist.
  logo: /gfx/svg/logo-2021.svg
  logo_footer: /gfx/svg/logo-footer.svg
  language: en-US
  cldnry: starbist

open_graph:
  pretty_url: true
  image: /gfx/jpg/social.jpg
  fb:
    fb_id: 340933169673372
    fb_admins: malimirkeccita
  twitter:
    twitter_id: malimirkeccita
  google_plus:
    google_plus_id: +SilvestarbistrovicFromHr

menu:
  centered: true
  display_logo: false
  items:
    Home: /
    Blog: /articles/
    Portfolio: /portfolio/
    About: /about-me/
    My links: /links/
    Contact →: /contact/

portfolio:
  title: Projects

sidebar:
  title: Quick Links
  items:
    About: /about-me/
    Hire me: /hire-me/
    Services: /services/
    Contact: /contact/
    Mentoring: https://mentor.silvestar.codes
    Setup: /uses/
    My Links: /links/
    Portfolio: /portfolio/
    Side Projects: /side-projects/
    CV: /portfolio/silvestar-bistrovic-cv.pdf
    # Toptal: https://www.toptal.com/resume/silvestar-bistrovic#trust-nothing-but-brilliant-freelancers
    LinkedIn: https://www.linkedin.com/in/starbist/
    GitHub: https://github.com/maliMirkec
    CodePen: https://codepen.io/CiTA/
    Twitter: https://twitter.com/malimirkeccita
    Silvestar Bistrović: /

cta1:
  span: "Looking for a mentor? Become a better UI developer today."
  btn1: "Join the program ⇢"
  btn2: "Start today"
  link: /contact/

cta2:
  span: "If you want me on your team, contact me today!"
  btn1: "Get in touch ⇢"
  btn2: "Open 2020 Q4"
  href: /contact/

widgets:
  # cookies: true
  about:
    paragraphs:
      - I am Silvestar Bistrović—fearless web engineer, CSS developer, JAMstack enthusiast, and WordPress theme specialist.
    contact:
      Contact: /contact/
      # Toptal: https://www.toptal.com/resume/silvestar-bistrovic#trust-nothing-but-brilliant-freelancers
      LinkedIn: https://www.linkedin.com/in/starbist/
      GitHub: https://github.com/maliMirkec
      CodePen: https://codepen.io/CiTA/
      Twitter: https://twitter.com/malimirkeccita
  subnav:
    Silvestar Bistrović: /
    Contact: /contact/
    # Toptal: https://www.toptal.com/resume/silvestar-bistrovic#trust-nothing-but-brilliant-freelancers
    LinkedIn: https://www.linkedin.com/in/starbist/
    GitHub: https://github.com/maliMirkec
    CodePen: https://codepen.io/CiTA/
    Twitter: https://twitter.com/malimirkeccita
    Feed: /rss2.xml
  disqus:
    shortname: silvestarbistrovic
  sharing:
    twitter: malimirkeccita
    facebook: silvestar.codes
    reddit: true
