[Settings]
ID = "33c0f310-012c-4821-9f39-9448f1a4b051"

[build]
  publish = "/public/"
  command = "npm run build-prod"

[context.production]
  command = "npm run build-prod"

[context.deploy-preview]
  command = "npm run build-dev"

[context.branch-deploy]
  command = "npm run build-dev"

[context.develop]
  command = "npm run build-dev"

[[plugins]]
  package = "netlify-plugin-submit-sitemap"

  [plugins.inputs]

  # The base url of your site (optional, default = main URL set in Netlify)
  baseUrl = "https://www.silvestar.codes"

  # Path to the sitemap URL (optional, default = /sitemap.xml)
  sitemapPath = "/sitemap.xml"

  # Enabled providers to submit sitemap to (optional, default = 'google', 'bing', 'yandex'). Possible providers are currently only 'google', 'bing', 'yandex'.
  providers = [
    "google",
    "bing",
    "yandex"
  ]
