[Settings]
ID = "33c0f310-012c-4821-9f39-9448f1a4b051"

[build]
  publish = "/_site/"
  command = "yarn deploy"

[context.production]
  command = "yarn deploy"

[context.deploy-preview]
  command = "yarn build"

[context.branch-deploy]
  command = "yarn build"

[context.develop]
  command = "yarn build"
