site:
  full_name: SB - Silvestar's personal website
  short_name: SB
  description: Silvestar Bistrović is fearless web developer and consultant, JAMstack enthusiast and Wordpress coder.
  logo: /gfx/svg/sb-white.svg
  language: en

home_page:
  - section:
    title: Silvestar Bistrović
    paragraphs:
     - Fearless web developer and consultant
     - JAMstack enthusiast
     - Wordpress coder
  - section:
    title: Specializations
    paragraphs:
      - Frontend Development
      - JAMstack
      - Wordpress
      - Page Speed Optimization
  - section:
    title: Links
    links:
      Github: //github.com/maliMirkec
      LinkedIn: //www.linkedin.com/in/starbist/
      Twitter: //twitter.com/malimirkeccita
      Codepen: //codepen.io/CiTA/
  - section:
    title: Projects
    links:
      Starter Project: //starter.silvestarbistrovic.from.hr
      Netki: /portfolio/netki/
      Han Han Xue: /portfolio/hanhanxue/
      Contiamo: /portfolio/contiamo/
      Irina and Matej: /portfolio/irinaandmatej/
  - section:
    title: Writing
    links:
      Gulp tasks for CSS: /articles/starter-project-gulp-tasks-for-css/
      A set of latest best practices packed in Gulp tasks: /articles/starter-project-a-set-of-latest-best-practices-packed-in-gulp-tasks/
      From Wordpress to Hexo: /articles/a-guide-to-static-site-generators-using-hexo-and-wordpress/
      Using CSS Grid Where Appropriate: /articles/using-css-grid-where-appropriate/
  - section:
    title: Available for hire
    links:
      Via Mail: mailto:me@silvestarbistrovic.from.hr?Subject=Inquiry
      Via Toptal: //www.toptal.com/resume/silvestar-bistrovic
      Via Upwork: //www.upwork.com/fl/silvestarb

open_graph:
  pretty_url: true
  image: /gfx/png/SB-big.png
  fb:
    fb_id: 340933169673372
    fb_admins: malimirkeccita
  twitter:
    twitter_id: malimirkeccita
  google_plus:
    google_plus_id: +SilvestarbistrovicFromHr

menu:
  centered: true
  display_logo: true
  items:
    Home: /
    Blog: /categories/articles
    Portfolio: /portfolio
    About: /about-me

widgets:
  contact:
    mail: mailto:me@silvestarbistrovic.from.hr?Subject=Hello
    linkedin: //www.linkedin.com/in/starbist/
    github: //github.com/maliMirkec
    codepen: //codepen.io/CiTA/
    medium: //medium.com/@malimirkeccita
    twitter: //twitter.com/malimirkeccita
    facebook: //www.facebook.com/silvestarbistrovic.from.hr/
    lastfm: //www.last.fm/user/maliMirkec
  disqus:
    shortname: silvestarbistrovic
  sharing:
    twitter: malimirkeccita
    facebook: silvestarbistrovic.from.hr
